### ISSUE TITLE
fatal error during install: boost/lexical_cast.hpp: No such file or directory

### ISSUE THREAD

**Issue by wjm1191** [vinhphunguyen/ofeFRAC#1]
Hi,

I was following the instructions to install ofFRAC in Linux. Fatal error message occurs: boost/lexical_cast.hpp: No such file or directory.

'In file included from ../src/util/utilities.cpp:20:
../src/util/utilities.h:20:10: fatal error: boost/lexical_cast.hpp: No such file or directory
   20 | #include <boost/lexical_cast.hpp>'

I checked the utilities.cpp line 20, which leads to utilities.h file. It includes '#include <boost/lexical_cast.hpp>' in line 20 of utilities.h file. However, there is no such folder 'boost' in source file, neither is the lexical_cast.hpp. Thanks for your help. Looking forward to the reply.

Best wishes

**Comment by vinhphunguyen** [comment]
You need to install boost first.

**Comment by wjm1191** [comment]
> You need to install boost first.

Thanks a lot. It works now.
